repository_type: pipeline

nf_core_version: 4.0.3

lint: {}

template:
  org: nf-core
  name: pathogenepidemiology
  description: A profile-based pipeline for genomic epidemiological analysis of predefined
    pathogens.
  author: Igiraneza Clement, Bilal Asser, Firas Zemzem, more tbc
  version: 0.1.0dev
  force: true
  outdir: .
  is_nfcore: true
